import { RELEASE_171 } from "./release";

export const CURRENT_VERSION = RELEASE_171 ? "1.7.1" : "1.7.0";

export type ChangeType = "nouveau" | "ameliore" | "corrige";

export interface ChangelogEntry {
  version: string;
  date: string;
  changes: { type: ChangeType; text: string }[];
}

// Ajoutez une nouvelle entrée EN HAUT de ce tableau à chaque mise à jour notable,
// à partir de maintenant (la version 1.0.0 ci-dessous est le tout premier lancement,
// regroupant tout ce qui a été construit avant la mise en ligne).
// CURRENT_VERSION doit toujours correspondre au numéro de la première entrée.
const ALL_ENTRIES: ChangelogEntry[] = [
  {
    version: "1.7.1",
    date: "Octobre 2026",
    changes: [
      { type: "nouveau", text: "Vidéos récompensées : regardez une publicité jusqu'au bout et touchez des pièces, jusqu'à cinq fois par jour. La récompense grandit avec votre compagnie (15 % d'une heure de recettes, de 20 à 400 pi.). C'est facultatif : rien ne s'interrompt pour une publicité" },
      { type: "nouveau", text: "Une bannière discrète en bas de quelques pages de consultation (classement, finances, progression, appels d'offres, cours) — jamais sur la carte, la flotte, la vue cabine ni pendant les premiers pas" },
      { type: "nouveau", text: "Boutique : le Coffret Belle Époque (voitures Pullman bordeaux filetées d'or, livrée, emblème de la lanterne et titre), le Coffret Grande Vitesse (rame au long nez profilé, livrée argent, emblème de la flèche et titre), la rame à deux niveaux, et les emblèmes de l'atelier" },
      { type: "nouveau", text: "Plaques d'honneur : votre nom encadré au classement, en laiton gravé, en émail bleu ou en or fin, vu par tous les joueurs. À essayer dans la vitrine de la boutique" },
      { type: "nouveau", text: "Billet sans pub : 1,99 € une fois pour toutes, et plus aucune bannière. Le bouton est juste au-dessus de la bannière. Si vous passez ensuite au Premium, il ne vous coûte plus qu'à partir de 4 €" },
      { type: "nouveau", text: "Premium — Aucune publicité : ni bannière, ni script publicitaire chargé tant que vous ne demandez pas vous-même une vidéo" },
      { type: "ameliore", text: "Le résumé du jour tient sur une ligne : le solde net, les trajets, les livraisons et les incidents, avec le détail des recettes et dépenses à déplier" },
    ],
  },
  {
    version: "1.7.0",
    date: "Octobre 2026",
    changes: [
      { type: "nouveau", text: "Arrêts intermédiaires : une ligne peut desservir jusqu'à quatre gares entre ses deux terminus. Chaque arrêt amène 20 % de voyageurs en plus et coûte une minute à quai. Sur la carte, on trace une ligne gare après gare" },
      { type: "nouveau", text: "Aller-retour : une rame fait l'aller puis le retour, et la carte, le tableau des rames et la vue cabine la montrent dans son vrai sens de marche, arrêt par arrêt" },
      { type: "nouveau", text: "Places et remplissage : chaque rame a un nombre de places (400 pour une Standard). Les voyageurs qui ne trouvent pas de place restent à quai, et plusieurs rames sur une même ligne se partagent la clientèle. Le tableau des lignes montre le remplissage de chacune, le tableau des rames les voyageurs du dernier trajet" },
      { type: "nouveau", text: "Prix du billet : réglable ligne par ligne, de ×0,6 à ×2. Plus cher, chaque voyageur rapporte plus mais il en vient moins. Le jeu indique le prix qui remplit juste vos rames" },
      { type: "nouveau", text: "Composition des rames : attelez jusqu'à trois voitures — 2de classe (+100 places), 1re classe (+60 places payées 1,8 fois) ou voiture-bar (+8 % de recette). Chaque voiture ralentit la rame de 3 %" },
      { type: "nouveau", text: "Infrastructures : achetez des gares (leurs commerces encaissent à chaque train qui s'y arrête, les autres compagnies y paient une redevance de quai, vos propres trajets y rapportent plus), ouvrez des ateliers régionaux (usure −25 % sur les lignes qui y passent) et électrifiez vos lignes (10 % plus rapides, usure −20 %). Une gare peut vous être rachetée au prix fort par un concurrent" },
      { type: "nouveau", text: "Banque : empruntez jusqu'à la moitié de la valeur de votre compagnie, sur un, trois ou sept jours. Remboursement automatique chaque heure, et la moitié des intérêts restants effacée si vous soldez en avance. Une échéance impayée coûte une pénalité et un point de réputation" },
      { type: "nouveau", text: "Bourse : chaque compagnie est cotée en 1000 actions. Achetez celles des autres (10 % au plus par compagnie), touchez des dividendes chaque soir à 20 h, revendez quand le cours a monté" },
      { type: "nouveau", text: "Rapport de la semaine : entrées, sorties, résultat d'exploitation, recettes ligne par ligne et comparaison avec la semaine d'avant. Une notification le lundi matin" },
      { type: "nouveau", text: "Heures de pointe : les voyageurs ne viennent plus à la même heure toute la journée. Beaucoup de monde de 7 h à 9 h et de 17 h à 19 h, moins l'après-midi, peu la nuit (les rames couchettes gardent leur service de nuit). Sur la journée, une ligne amène autant de voyageurs qu'avant, mais une rame trop petite déborde à la pointe et roule à moitié vide au creux. La page Lignes montre l'affluence heure par heure" },
      { type: "nouveau", text: "Carrière agrandie : quatre grades de plus après la Légende du rail — Bâtisseur de gares, Maître des caténaires, Magnat européen et Empereur du rail. Il faut posséder des gares, ouvrir des ateliers, électrifier ses lignes et passer les six frontières. Chacun donne son nom en titre à afficher au classement" },
      { type: "nouveau", text: "Premium — Prix automatique : sur les lignes de votre choix, le billet se recale sur le prix qui remplit juste vos rames, à chaque changement d'heure pour suivre la pointe" },
      { type: "nouveau", text: "Premium — Remplissage heure par heure : la courbe des 24 dernières heures de chaque ligne, l'heure de pointe et les voyageurs restés à quai" },
      { type: "nouveau", text: "Premium — Bourse : ordres automatiques (acheter sous un cours, vendre au-dessus), exécutés même jeu fermé, et la liste de vos actionnaires" },
      { type: "nouveau", text: "Premium — Rapport sur quatre semaines et export en tableur (CSV)" },
      { type: "nouveau", text: "Premium — Alertes : une gare qui sort de sa protection, une gare rachetée par un concurrent, une échéance que la trésorerie ne couvrira pas" },
      { type: "nouveau", text: "Premium — Vos gares à vos couleurs sur la carte, et vos voitures de 1re classe peintes à votre livrée dans la vue cabine" },
      { type: "nouveau", text: "12 nouveaux succès, 100 en tout : omnibus, salle comble, rame longue, chef de gare, fil de contact, atelier régional, bon payeur, actionnaire, heure de pointe, heures creuses, bâtisseur et empereur du rail" },
      { type: "ameliore", text: "Nouvelle interface : le menu et les en-têtes de page prennent les codes de la signalétique de gare — pictogrammes dans leur carré, onglets et tableaux façon tableau des départs" },
      { type: "ameliore", text: "« Comptes » devient « Finances » : rapport de la semaine, rentabilité, banque, bourse et grand livre au même endroit" },
      { type: "ameliore", text: "La valeur des compagnies au classement compte les gares, les ateliers et les actions détenues, et retranche ce qui est dû à la banque" },
    ],
  },
  {
    version: "1.6.0",
    date: "Octobre 2026",
    changes: [
      { type: "nouveau", text: "Lignes internationales : Londres, Bruxelles, Francfort, Genève, Milan et Barcelone rejoignent la carte. Avec la licence internationale (grade « Baron du rail » et 6 000 pi., une fois pour toutes), vos lignes passent la frontière : recette ×1,6 par trajet, dont 25 % reversés en péage de sillon au réseau étranger" },
      { type: "nouveau", text: "Trains de nuit : la rame couchettes (dès « Chef de réseau », 900 pi.) roule sur les grandes lignes de 10 minutes et plus. De 22 h à 6 h, heure de Paris, chacun de ses trajets rapporte trois fois plus ; le jour, 20 % de moins qu'une rame assise" },
      { type: "nouveau", text: "Application installable : Réseau s'installe sur l'écran d'accueil du téléphone ou de l'ordinateur, sans passer par un store. Son icône, sa fenêtre, un écran de démarrage, et les notifications sur iPhone. Le bouton est dans le menu et dans les paramètres" },
      { type: "nouveau", text: "Décisions : de temps en temps, une situation arrive sur votre bureau. Une grève en gare, une fissure sur une rame, un festival, un maire qui veut sa ligne, un concurrent qui casse les prix… Deux ou trois réponses, chacune avec son prix, et deux heures pour trancher. Sans réponse, le réseau tranche pour vous, rarement en votre faveur. Une notification prévient quand une décision arrive, jamais la nuit" },
      { type: "nouveau", text: "Le fil du réseau : la barre du haut fait défiler ce qui se passe, vos rames qui arrivent, les lignes que les autres compagnies ouvrent, les salons et les grèves en gare. Et quand l'argent rentre, « +48 pi. » s'affiche au-dessus de la trésorerie" },
      { type: "nouveau", text: "Premium — Licence internationale en avance : les abonnés peuvent l'acheter dès aujourd'hui, une semaine avant l'ouverture à tous" },
      { type: "nouveau", text: "11 nouveaux succès, 88 en tout : passeport ferroviaire, passage de frontière, sous la Manche, tour d'Europe, train de nuit, nuit blanche, sur l'écran d'accueil, premiers pas, premier arbitrage, le bureau du directeur et promesse tenue" },
      { type: "ameliore", text: "Nouveaux joueurs : un vrai écran de fondation (nom, livrée, ce qui vous attend), un guide plus court, trois idées de première ligne, et la liste « Premiers pas » qui mène de la première ligne à la première correspondance. Les rubriques du menu apparaissent quand elles deviennent utiles, et chacune s'explique la première fois qu'on l'ouvre" },
      { type: "ameliore", text: "Nouvelle carte : elle occupe tout l'écran et se manipule comme celle d'un jeu. On la fait glisser, on zoome à la molette, au pincement ou aux boutons, et plus on s'approche, plus elle montre de gares et de détails. Une gare ou une rame se touche pour ouvrir sa fiche : demande, événements, correspondance, « Tracer une ligne d'ici », ou « Suivre la rame ». Échelle en kilomètres, plein écran, légende et liste des lignes en panneaux repliables" },
      { type: "ameliore", text: "La carte prend du relief et ses vraies proportions : fleuves, massifs, quadrillage, lignes en trait plein, rames à la couleur de leur ligne qui laissent une traînée, et l'affluence d'une gare affichée en clair (« +35 % »). La nuit, la carte s'assombrit et les villes s'allument" },
      { type: "nouveau", text: "Premium — En direct : la vue cabine s'installe en tête de votre flotte. Une de vos rames en route, filmée de profil, qui change toutes les vingt secondes, avec sa vitesse et l'heure d'arrivée. Les flèches passent à la suivante, « Agrandir » ouvre la grande vue cabine" },
      { type: "ameliore", text: "Le nom d'une ligne devient facultatif : elle prend celui de ses deux gares" },
      { type: "ameliore", text: "Nouvel écran de connexion : une carte, deux onglets, le mot de passe qu'on peut afficher, « Rester connecté », et selon ce qui est activé sur le serveur, « Mot de passe oublié ? », la vérification Cloudflare et la connexion avec Discord ou Google. L'adresse e-mail ne tient plus compte des majuscules" },
      { type: "ameliore", text: "Les appels d'offres rejoignent le Commerce dans le menu, avec le fret et le cours des marchandises" },
      { type: "ameliore", text: "Quand une nouvelle version est en ligne, un bandeau propose de recharger la page : plus besoin de fermer l'onglet pour en profiter" },
      { type: "corrige", text: "Affecter une rame depuis le bas de l'écran pouvait ne rien faire : le menu se fermait avant que le choix ne parte. Et le tableau des rames ne se réordonne plus tout seul à chaque rafraîchissement" },
      { type: "corrige", text: "Un double clic sur « Réviser » envoyait deux révisions ; le bouton est aussi grisé quand la trésorerie ne suffit pas" },
      { type: "ameliore", text: "La carte s'ouvre sur l'Europe : le Royaume-Uni, la Belgique, l'Allemagne, la Suisse, l'Italie et l'Espagne entourent la France, avec la Manche, la mer du Nord et la Méditerranée, et les gares étrangères y trouvent leur place. Le formulaire de ligne indique la recette nette d'une ligne internationale et les grandes lignes où une rame couchettes peut rouler" },
      { type: "ameliore", text: "La vue cabine montre les rames couchettes, rideaux à moitié tirés, et le bandeau du réseau signale le service de nuit" },
      { type: "ameliore", text: "Grand livre et rentabilité : les péages de sillon et la licence ont leur ligne, et le péage est déduit de ce que rapporte une ligne internationale" },
    ],
  },
  {
    version: "1.5.0",
    date: "Septembre 2026",
    changes: [
      { type: "nouveau", text: "Appels d'offres : chaque semaine, trois régions cherchent une compagnie pour exploiter une liaison. Si vous exploitez la liaison, déposez une offre du lundi au mardi (la subvention que vous demandez par jour, sous pli fermé). Le mercredi, la moins chère l'emporte, pondérée par la réputation, et touche sa subvention jusqu'au lundi suivant, chaque heure où ses rames roulent sur la liaison" },
      { type: "nouveau", text: "Chaque marché demande un nombre de trajets : objectif atteint, prime d'une journée ; objectif manqué, pénalité d'une demi-journée, sans jamais mettre votre trésorerie dans le rouge" },
      { type: "nouveau", text: "Correspondances : une gare d'où vos rames partent vers plusieurs destinations rapporte plus, +4 % par destination au-delà de la première, jusqu'à +12 % par gare. Le formulaire de création montre la correspondance qu'ouvrirait une nouvelle ligne, et la carte les marque d'un losange" },
      { type: "nouveau", text: "Temps forts de saison : les Vendanges (Bordeaux, Reims, Dijon, Avignon, Tours, Mulhouse), les Marchés de Noël, les Vacances de neige et les Grandes Vacances font grimper la demande de leurs gares pendant plusieurs semaines" },
      { type: "nouveau", text: "Boutique : un coffret en édition limitée par temps fort (livrée et emblème), en vente seulement pendant sa saison. Le premier, le Coffret des Vendanges, est disponible jusqu'au 31 octobre" },
      { type: "nouveau", text: "Premium — Appels d'offres en avance : les marchés de la semaine suivante dès le dimanche, le nombre d'offres déjà déposées sur chaque marché (jamais les montants) et une notification du résultat" },
      { type: "nouveau", text: "11 nouveaux succès, 77 en tout : premier marché, adjudicataire, contrat rempli, au plus juste, première correspondance, nœud ferroviaire, étoile ferroviaire, et un succès par temps fort — vendangeur, esprit de Noël, neiges éternelles, grandes vacances — qui ne se gagne que pendant sa saison" },
      { type: "nouveau", text: "Réseau a son compte Instagram, @reseau.lejeu : les nouveautés en avant-première et les coulisses du jeu. Le lien est en bas du menu, sur la page d'accueil et dans ce bulletin" },
      { type: "ameliore", text: "Nouveau logo : le R de Réseau tracé comme une ligne, avec le losange des correspondances. Il remplace l'ancien sur le site, l'icône de l'application installée, l'onglet du navigateur et les notifications" },
      { type: "ameliore", text: "Menu rangé par thème (Exploitation, Commerce, Compagnie) et toujours visible quand on fait défiler une page. Missions rejoint le Fret, l'Historique rejoint la Rentabilité dans « Comptes », et les Succès rejoignent la Carrière dans « Progression » : douze rubriques au lieu de quinze" },
      { type: "nouveau", text: "Boutique en vitrine : votre rame est exposée en gare, de nuit, et l'article choisi s'applique dessus en direct — la livrée sur la caisse, l'emblème sur la motrice, le titre sur la plaque du quai, la loco à vapeur ou la Micheline à la place de la rame. On essaie chaque variante avant d'acheter, et on porte d'un clic ce qu'on possède déjà. L'habillage s'essaie sur toute la console" },
      { type: "corrige", text: "La suppression de compte échouait pour une compagnie qui avait utilisé les missions, l'entrepôt, les alertes de cours ou la boutique : toutes ses données sont maintenant effacées" },
      { type: "ameliore", text: "Fret, Missions et Cours ont chacun leur icône, et une demande d'augmentation du personnel s'affiche par un point dans le menu" },
    ],
  },
  {
    version: "1.4.0",
    date: "Septembre 2026",
    changes: [
      { type: "nouveau", text: "Les gares ont une taille : Paris, les huit métropoles, les grandes villes, les villes moyennes et les petites. Une ligne rapporte selon ses deux gares — une liaison vers la capitale paie plus qu'une desserte de petites villes" },
      { type: "nouveau", text: "Événements de gare : salons, matchs, festivals, afflux touristiques font grimper la demande d'une gare pendant quelques heures ; grèves et travaux la font baisser. Ils s'affichent sur la page des lignes et sur la carte" },
      { type: "nouveau", text: "Concurrence : si plusieurs compagnies exploitent la même liaison, elles se partagent les voyageurs. La plus attractive — réputation, nombre de rames, rames Express, rames en bon état — en prend aux autres, jusqu'à +40 % pour elle et −40 % pour la moins bonne. À attractivité égale, personne ne perd rien" },
      { type: "nouveau", text: "Chaque ligne affiche sa demande et votre part des voyageurs, et la carte montre les liaisons exploitées par les autres compagnies" },
      { type: "nouveau", text: "Avant de tracer une ligne, vous voyez la taille des deux gares, leur demande du moment et si une autre compagnie y roule déjà" },
      { type: "nouveau", text: "Premium — Vue cabine : suivez n'importe laquelle de vos rames en direct, de profil, du départ jusqu'à l'arrêt sous le panneau de la gare d'arrivée. Sa vraie position sur la ligne, la météo du réseau, la nuit, votre livrée et son modèle. En gratuit, un aperçu de quelques secondes" },
      { type: "nouveau", text: "Premium — Veille concurrentielle : le détail de chaque concurrent sur vos lignes (réputation, rames Express, état des rames) et une notification quand une compagnie arrive sur votre ligne ou vous passe devant" },
      { type: "nouveau", text: "Premium — Événements annoncés : les abonnés voient chaque événement de gare une heure avant qu'il commence, le temps de placer leurs rames" },
      { type: "nouveau", text: "11 nouveaux succès, 66 en tout : face à face, tête de ligne, ligne disputée, tous les chemins mènent à Paris, les grandes métropoles, desserte fine, le bon moment, en cabine, directeur régional, légende du rail et un nom qui compte" },
      { type: "nouveau", text: "Boutique : quatre nouveaux objets — Livrées régionales (bleu Bretagne, rouge Alsace, lavande de Provence, vert Normandie), Emblèmes du réseau (rail, boussole, horloge de gare, viaduc), Titres de légende, et le Matériel de collection : une locomotive à vapeur et son panache, ou une Micheline rouge et crème, dans la vue cabine. Toujours purement cosmétique" },
      { type: "nouveau", text: "Carrière agrandie : cinq grades de plus après le Magnat — Directeur régional, Directeur national, Administrateur des chemins de fer, Président de compagnie et Légende du rail. Ils demandent un réseau étendu, du fret, une équipe et une réputation, pas seulement de l'argent. Chacun donne son nom en titre à afficher au classement" },
      { type: "nouveau", text: "La neige arrive, seulement en hiver (décembre à février) : elle ralentit les rames et rend les retards plus fréquents. La météo suit maintenant les saisons — verglas de novembre à mars, canicule de mai à septembre, brouillard toute l'année" },
      { type: "ameliore", text: "La météo se voit vraiment : flocons qui tombent et s'amassent en bas de l'écran, nappes de brouillard qui dérivent, givre qui gagne depuis les bords, lumière écrasante de canicule. Chaque épisode arrive et repart en fondu, et le centre de l'écran reste lisible" },
      { type: "corrige", text: "Le classement « Fret de la semaine » comptait les sept derniers jours glissants : il repart maintenant de zéro chaque lundi à 0 h (heure de Paris)" },
      { type: "ameliore", text: "La page Carrière montre la progression de chaque condition du grade suivant (« 12 / 20 gares »), l'avancement global et ce que chaque grade débloque" },
      { type: "corrige", text: "Sur la carte, les trains roulaient en ligne droite à côté de leur voie courbe, et avançaient par à-coups. Ils suivent maintenant exactement le tracé de leur ligne, en continu" },
      { type: "corrige", text: "Un titre gagné en jeu ne pouvait être porté qu'après avoir acheté un objet en boutique" },
      { type: "ameliore", text: "La liste des avantages Premium dans les Paramètres était restée à la 1.2 : elle présente maintenant tout ce que le Premium comprend" },
    ],
  },
  {
    version: "1.3.0",
    date: "Septembre 2026",
    changes: [
      { type: "nouveau", text: "Boutique : livrées, emblèmes de compagnie, titres au classement et un troisième habillage, « Plan 1935 ». Chaque objet s'achète une fois. Aucun ne rapporte une pièce ni n'accélère un chantier" },
      { type: "nouveau", text: "Emblème et titre se choisissent librement parmi ceux que vous possédez, et s'affichent dans la console comme au classement" },
      { type: "nouveau", text: "Notifications : prévenu quand un chantier se termine, qu'un ordre permanent s'exécute ou qu'un cours franchit votre seuil — même jeu fermé. À activer depuis les Paramètres, appareil par appareil" },
      { type: "nouveau", text: "Premium — Rentabilité : recettes, réparations, pannes et bénéfice à l'heure de chaque ligne et de chaque rame sur sept jours, avec le détail jour par jour. Pour savoir où placer la prochaine rame, et laquelle coûte plus qu'elle ne rapporte" },
      { type: "nouveau", text: "Premium — Bilan de retour : après trois heures d'absence, un écran résume ce qui s'est passé et ce qui attend une décision (rames à l'arrêt, demandes d'augmentation, chantiers livrés, cours). Avec les notifications activées, un résumé de la nuit arrive aussi chaque matin vers 8 h" },
      { type: "nouveau", text: "Premium — File de chantiers : pendant un chantier, on peut préparer le suivant. Il est payé à la commande et démarre tout seul à la fin du premier, même la nuit. Il ne va pas plus vite, et on peut le retirer de la file contre remboursement" },
      { type: "nouveau", text: "Personnel : chaque employé a un nom et gagne de l'expérience en service — niveau 2 après 6 h, jusqu'au niveau 5 après une semaine. À chaque palier il demande une augmentation : l'accorder le rend plus efficace et plus cher, la refuser le laisse à son niveau" },
      { type: "nouveau", text: "Plusieurs mécaniciens et chefs de dépôt par compagnie. Chacun couvre un nombre de rames (4 à 8 pour un mécanicien, 6 à 10 pour un chef de dépôt, selon son niveau) : la page Personnel indique combien de rames sont couvertes sur votre flotte. Le directeur commercial reste unique" },
      { type: "ameliore", text: "Vos employés actuels gardent leur ancienneté, convertie en expérience : les plus anciens vous présenteront leur demande d'augmentation dès la mise à jour" },
      { type: "ameliore", text: "Chômage technique : mécaniciens et chefs de dépôt ne sont plus payés quand aucune rame ne roule — une flotte de fret à quai pendant la nuit ne coûte plus une équipe entière à rien faire" },
      { type: "ameliore", text: "Chaque fiche d'employé indique ce qu'il fait économiser à l'heure, à côté de ce qu'il coûte" },
      { type: "ameliore", text: "Attention aux grandes flottes : un mécanicien seul ne protège plus que 4 rames, les autres s'usent au tarif normal. Au-delà, il faut embaucher" },
      { type: "nouveau", text: "Vingt nouvelles gares — Brest, Caen, Amiens, Reims, Troyes, Orléans, Tours, Angers, Poitiers, La Rochelle, Limoges, Clermont-Ferrand, Saint-Étienne, Besançon, Avignon, Montpellier, Nice, Perpignan, Pau et Bayonne. Le réseau passe de 18 à 38 gares, et la plus longue ligne possible relie désormais Brest à Nice" },
      { type: "nouveau", text: "Le fret part de nouvelles régions : chaque marchandise a maintenant plusieurs itinéraires, avec une durée tirée de la distance réelle et le même tarif à la minute" },
      { type: "nouveau", text: "17 nouveaux succès, 55 en tout : le réseau (15 puis 30 gares, Brest, le Train bleu Paris–Nice, Brest–Nice), le personnel (première augmentation, un vétéran de niveau 5, quatre mécaniciens, une flotte entièrement couverte), les révisions préventives, et de plus grands objectifs de trésorerie, de fret, de défis et d'ancienneté" },
      { type: "nouveau", text: "Révision préventive : une rame peut être réparée avant la panne, sans s'arrêter. Le coût reste proportionnel à l'usure" },
      { type: "ameliore", text: "La réparation automatique n'est plus réservée aux abonnés : toute rame en panne est réparée d'office si la trésorerie suit. Elle faisait rouler la flotte d'un abonné la nuit quand celle d'un joueur gratuit s'arrêtait — un avantage de revenu que le Premium ne devait pas donner" },
      { type: "ameliore", text: "Premium : les alertes de cours et les ordres permanents prennent la place de la réparation automatique dans la liste des avantages" },
      { type: "corrige", text: "Une rame réparée automatiquement repassait à quai au lieu de reprendre sa ligne : elle s'arrêtait net. Elle repart désormais comme après une réparation manuelle" },
      { type: "corrige", text: "Le fret n'usait pas les rames : une rame affectée aux livraisons roulait indéfiniment sans jamais tomber en panne. L'usure s'applique désormais des deux côtés, mécanicien et canicule compris" },
      { type: "corrige", text: "L'effet du mécanicien disparaissait par arrondi quand l'usure d'un tour était faible — en pleine canicule, il ne servait à rien. Il s'applique désormais à chaque tour, même sur de petites valeurs" },
      { type: "corrige", text: "Notifications : l'essai dit maintenant si l'envoi a réussi et pourquoi il échoue, un appareil dont l'abonnement s'était perdu est réabonné tout seul à l'ouverture du jeu, et sur iPhone la page explique comment installer le jeu sur l'écran d'accueil — la seule façon d'y recevoir des notifications" },
      { type: "corrige", text: "La trésorerie était coupée en haut du tableau de bord : 4 820 pi. s'affichait « 482 ». Elle a maintenant une colonne plus large, des chiffres qui s'adaptent à l'écran, et prend toute la première ligne sur téléphone" },
      { type: "corrige", text: "« Duo gagnant » et « Équipe complète » comptent les postes pourvus, et non les personnes : trois mécaniciens ne font pas une équipe complète" },
      { type: "corrige", text: "Un retard sur le fret ne retardait rien et faisait sauter l'usure du tour. Il décale maintenant vraiment la livraison" },
      { type: "corrige", text: "La fin d'un chantier s'annonçait une fois par seconde jusqu'à la mise en service, et le compte à rebours affichait « terminé restant »" },
      { type: "corrige", text: "Une notification en échec pouvait bloquer la livraison de tous les chantiers du réseau" },
      { type: "corrige", text: "La page d'accueil annonçait encore un dépôt limité à six rames et des rames immobilisées à la moindre panne" },
    ],
  },
  {
    version: "1.2.0",
    date: "Septembre 2026",
    changes: [
      // --- l'économie et le temps long ---
      { type: "nouveau", text: "Donneurs d'ordre : quatre chargeurs vous confient des ordres de fret datés, à accepter ou à refuser. Les honorer fait monter votre réputation chez eux, qui majore le tarif de toutes leurs cargaisons jusqu'à +25 %. Un ordre accepté puis non tenu coûte leur confiance ; le refuser ne coûte rien" },
      { type: "nouveau", text: "Cours du fret : les neuf marchandises ont un prix qui monte et descend, commun à tout le réseau, avec la courbe des huit dernières heures et les événements qui l'expliquent — grève au port, récolte abondante, commande publique de rails" },
      { type: "nouveau", text: "Entrepôt : acheter bas, garder, revendre haut. La capacité limite la mise, les frais de garde font payer l'attente" },
      { type: "nouveau", text: "Livrer une marchandise recherchée paie plus : de −19 % à +24 % selon le cours du jour, affiché sur chaque contrat" },
      { type: "nouveau", text: "Chantiers : entrepôt, agrandissements et places de dépôt se construisent. On paie à la commande, la livraison vient plus tard, et on ne mène qu'un chantier à la fois" },
      { type: "nouveau", text: "Le dépôt n'a plus de plafond, mais chaque place coûte 1,7 fois la précédente — 1 670 pi. pour la 7e, 8 207 pour la 10e — et demande un chantier plus long" },
      { type: "nouveau", text: "Entretien du réseau : une charge qui croît avec le carré de votre parc, les deux premières rames exonérées. Votre compagnie a désormais une taille optimale, vers quatorze rames" },
      { type: "nouveau", text: "Le rendement d'une ligne croît avec sa longueur : de +0 % à 3 minutes de trajet jusqu'à +25 % à 20 minutes" },

      // --- la carte, l'équipement, l'abonnement ---
      { type: "nouveau", text: "Tracez une ligne directement sur la carte : cliquez deux gares, la distance et la durée se calculent toutes seules" },
      { type: "nouveau", text: "Les rames Express et Fret Lourd et le poste de Directeur commercial dépendent maintenant de votre grade et non de l'abonnement. Personne n'avait jamais pu les acheter : aucune compagnie ne pouvait devenir Premium" },
      { type: "nouveau", text: "Premium repensé : deux ordres par donneur d'ordre, six contrats de fret au lieu de quatre, réparation automatique des rames en panne, −20 % sur les places de dépôt, livrées réservées, alertes de cours, ordres permanents et cinq marchandises stockées en parallèle. Aucun bonus de revenu, aucun chantier accéléré" },
      { type: "nouveau", text: "Deux habillages au choix, Nuit et Papier, enregistrés sur votre compte" },

      // --- classement, parrainage, progression ---
      { type: "nouveau", text: "Quatre classements au lieu d'un : valeur de la compagnie, fret de la semaine, ponctualité, parrains. Votre position s'affiche toujours, même hors du top 20, avec l'écart qui vous sépare de la compagnie devant vous" },
      { type: "nouveau", text: "Paliers de parrainage : une place de dépôt à 3 filleuls, le titre « Recruteur du rail » à 5, une rame Express offerte à 10. Le bandeau de la flotte donne un message tout prêt et la progression" },
      { type: "nouveau", text: "16 nouveaux succès et un défi quotidien qui passe de 3 à 15 modèles, tirés parmi ceux à la portée de votre grade" },
      { type: "nouveau", text: "Chaque nouveauté s'explique la première fois que vous ouvrez sa page, et l'explication est mémorisée sur votre compte" },

      { type: "ameliore", text: "Le classement principal repose sur la valeur totale de la compagnie — trésorerie, matériel et dépôt réunis : acheter une rame ne vous fait plus reculer" },
      { type: "ameliore", text: "La ponctualité n'est classée qu'à partir de dix trajets, et le grade de chaque compagnie est visible au classement" },
      { type: "ameliore", text: "La durée d'un trajet découle de la distance réelle entre les deux gares. Vos lignes existantes ont été recalculées" },
      { type: "ameliore", text: "Tutoriel refondu : huit étapes, dont trois qui attendent que vous agissiez vraiment. Pendant ces étapes, l'interface reste entière et cliquable" },
      { type: "ameliore", text: "La flotte affiche l'entretien horaire du réseau, le prix et la durée du prochain chantier de dépôt" },
      { type: "ameliore", text: "Bulletin de service refait : toutes les versions sont consultables, les lignes regroupées par nature" },
      { type: "ameliore", text: "Vous êtes prévenu quand un filleul rejoint le réseau, quand la prime tombe et quand un palier est atteint" },

      { type: "corrige", text: "L'usure réduite promise aux abonnés ne faisait rien : l'arrondi ramenait 2 × 0,3 et 2 ÷ 2 à la même valeur. Le mécanicien est enfin pleinement utile" },
      { type: "corrige", text: "Un « retard » ne retardait rien : la progression étant calculée depuis l'heure de départ, l'incident faisait même sauter l'usure du tour" },
      { type: "corrige", text: "Le marché garantit la présence de la marchandise réclamée par un ordre en cours : un ordre ne peut plus devenir infaisable sans votre faute" },
      { type: "corrige", text: "Une cargaison endommagée en route ne compte plus pour un ordre de mission" },
      { type: "corrige", text: "Un faux compte ne rapporte plus de palier : seuls les filleuls ayant atteint le grade « Gestionnaire confirmé » comptent" },
      { type: "corrige", text: "La page d'accueil débordait horizontalement sur téléphone, et ses avantages Premium dataient du lancement" },
      { type: "corrige", text: "Classement et progression de parrainage sont mis en cache côté serveur, pour alléger la base de données" },
    ],
  },
  {
    version: "1.1.0",
    date: "Septembre 2026",
    changes: [
      { type: "nouveau", text: "Carrière : cinq grades à franchir, chacun débloqué par une chaîne d'objectifs précis" },
      { type: "nouveau", text: "Assurance fret : réduisez le risque de dommage d'une cargaison fragile contre une prime" },
      { type: "nouveau", text: "8 nouveaux succès : vétéran du rail, passage au Premium, flotte diversifiée, équipe complète, assurance, grand réseau et champion du réseau" },
      { type: "nouveau", text: "Parrainage : invitez des amis avec votre code, 100 pi. pour eux, 150 pi. pour vous une fois qu'ils ont vraiment commencé à jouer" },
      { type: "ameliore", text: "Le modèle de chaque rame (Standard, Express, Fret Lourd) est maintenant visible dans la flotte" },
      { type: "ameliore", text: "Le tutoriel est désormais mémorisé sur votre compte, plus seulement sur votre navigateur" },
      { type: "ameliore", text: "Le fret peut désormais subir des retards comme les lignes voyageurs, et la météo l'affecte enfin aussi" },
      { type: "corrige", text: "Réduction du taux d'incidents, devenu excessif sur les lignes longues" },
      { type: "corrige", text: "Coût de réparation réduit, pour éviter qu'une double panne ne bloque un nouveau joueur sans argent" },
      { type: "corrige", text: "Les succès restent désormais acquis pour toujours, même si la condition qui les a débloqués ne l'est plus" },
      { type: "corrige", text: "Correction de plusieurs bugs d'affectation de trains et de menus déroulants" },
      { type: "corrige", text: "Le tutoriel ne masque plus le bouton d'achat quand le catalogue est déjà ouvert" },
      { type: "corrige", text: "Le tutoriel ne bloque plus le formulaire de création de ligne" },
    ],
  },
  {
    version: "1.0.0",
    date: "Septembre 2026",
    changes: [
      { type: "nouveau", text: "Fondez votre compagnie, tracez vos lignes et gérez votre flotte de trains" },
      { type: "nouveau", text: "Fret et contrats de marchandises, y compris les cargaisons fragiles à risque" },
      { type: "nouveau", text: "Personnel de compagnie (mécanicien, chef de dépôt) et statut Premium (rames Express et Fret Lourd, Directeur commercial)" },
      { type: "nouveau", text: "Météo dynamique et réputation influençant vos revenus" },
      { type: "nouveau", text: "Classement national, succès à débloquer et défi quotidien" },
      { type: "nouveau", text: "Carte du réseau en direct et tutoriel guidé" },
      { type: "nouveau", text: "Page d'accueil publique avec présentation du jeu et des offres" },
    ],
  },
];

// la 1.7.1 n'apparaît qu'une fois sortie (src/release.ts)
export const CHANGELOG: ChangelogEntry[] = ALL_ENTRIES.filter((e) => RELEASE_171 || e.version !== "1.7.1");
